[package]
name = "defi-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.12.6", features = ["full"] }
eyre = "0.6.12"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
